# Generated by Django 6.1.1 on 2026-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text="Scheduled date for this puzzle. You don't have to schedule every date — services.get_daily_puzzle deterministically picks an active puzzle from the pool for any day that has nothing scheduled.", unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pull this puzzle out of rotation without deleting it.')),
                ('sport', models.CharField(choices=[('NBA', 'NBA'), ('NFL', 'NFL'), ('MLB', 'MLB'), ('NHL', 'NHL'), ('GENERAL', 'General')], default='NBA', max_length=16)),
                ('category', models.CharField(choices=[('PLAYER', 'Player'), ('TEAM', 'Team'), ('SEASON', 'Season'), ('GAME', 'Game'), ('RECORD', 'Record')], default='PLAYER', max_length=16)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=16)),
                ('answer', models.CharField(help_text='The canonical, display-ready answer.', max_length=200)),
                ('accepted_answers_extra', models.CharField(blank=True, help_text='Comma-separated alternate answers/aliases, e.g. "LeBron, Bron, King James". The canonical answer above is always accepted automatically — don\'t repeat it here.', max_length=500)),
                ('clue_1', models.CharField(help_text='Shown first. Start obscure.', max_length=280)),
                ('clue_2', models.CharField(blank=True, max_length=280)),
                ('clue_3', models.CharField(blank=True, max_length=280)),
                ('clue_4', models.CharField(blank=True, max_length=280)),
                ('clue_5', models.CharField(blank=True, max_length=280)),
                ('clue_6', models.CharField(blank=True, max_length=280)),
                ('clue_7', models.CharField(blank=True, max_length=280)),
                ('clue_8', models.CharField(blank=True, help_text='Last resort. Most obvious.', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
